import feedparser
import os
import requests
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

# ----------------------
# 配置（从 GitHub Secrets 读取）
# ----------------------
DEEPSEEK_API_KEY = os.getenv("DEEPSEEK_API_KEY")
SENDER_EMAIL = os.getenv("SENDER_EMAIL")
SENDER_PASSWORD = os.getenv("SENDER_PASSWORD")
RECEIVER_EMAIL = os.getenv("RECEIVER_EMAIL")
SERVERCHAN_SENDKEY = os.getenv("SERVERCHAN_SENDKEY")

DEEPSEEK_API_URL = "https://api.deepseek.com/v1/chat/completions"
SERVERCHAN_URL = f"https://sctapi.ftqq.com/{SERVERCHAN_SENDKEY}.send"

# ----------------------
# 资讯源（半导体 / AI / 存储 / DRAM / NAND / 公司新闻）
# ----------------------
NEWS_FEEDS = {
"半导体行业（专业媒体）": [
"https://www.eet-china.com/rss/news.xml",
"https://www.eejournal.com/rss-feeds/",
"https://www.digitimes.com/rss/news.xml",
"https://www.trendforce.com/rss/news.xml",
"https://www.wsts.org/feed/"
],
"人工智能": [
"https://techcrunch.com/feed/",
"https://www.artificialintelligence-news.com/rss/",
"https://ai.googleblog.com/atom.xml"
],
"存储产业 / DRAM / SSD": [
"https://www.storagereview.com/rss",
"https://www.anandtech.com/rss/",
"https://www.dramx.com/rss"
],
"DRAM / NAND 价格趋势": [
"https://www.dramx.com/rss",
"https://www.trendforce.com/rss/dram-nand-price.xml"
],
"公司新闻": {
"NVIDIA": [
"https://blogs.nvidia.com/feed/",
"https://www.nvidia.com/en-us/news/rss/"
],
"台积电 TSMC": [
"https://www.tsmc.com/rss/news.xml"
],
"三星 Samsung": [
"https://news.samsung.com/global/rss/news.xml"
],
"美光 Micron": [
"https://www.micron.com/rss/news.xml"
],
"长江存储 Yangtze Memory": [
"https://www.ymtc.com/en/news/rss/"
],
"中芯国际 SMIC": [
"https://www.smic.com/en/news-center/rss/"
]
}
}

# ----------------------
# 1. 抓取新闻
# ----------------------
def fetch_news():
all_news = []

for category, feeds in NEWS_FEEDS.items():
if category == "公司新闻":
for company, company_feeds in feeds.items():
for feed in company_feeds:
try:
d = feedparser.parse(feed)
for entry in d.entries[:3]:
all_news.append({
"category": f"公司新闻 - {company}",
"title": entry.title,
"summary": entry.summary,
"link": entry.link
})
except Exception as e:
print(f"Error fetching {feed}: {e}")
else:
for feed in feeds:
try:
d = feedparser.parse(feed)
for entry in d.entries[:5]:
all_news.append({
"category": category,
"title": entry.title,
"summary": entry.summary,
"link": entry.link
})
except Exception as e:
print(f"Error fetching {feed}: {e}")

return all_news

# ----------------------
# 2. DeepSeek 中英双语总结（含 Implication）
# ----------------------
def summarize_news(news):
news_text = "\n\n".join([
f"分类: {n['category']}\n标题: {n['title']}\n摘要: {n['summary']}\n链接: {n['link']}"
for n in news
])

prompt = f"""
你是半导体、AI、存储行业的资深分析师。
请对以下新闻进行 **中英双语总结**，并为每条新闻提供 **Implication（行业影响分析）**。

要求：
1. 每条新闻包含：
- 中文总结（2～3 句话）
- English summary (2～3 sentences)
- Implication（1～2 句话，分析对产业链、市场、技术的影响）
2. 按分类整理
3. 语言专业但不晦涩
4. 对 DRAM / NAND 价格趋势新闻要重点分析市场影响
5. 最后给出“今日行业要点总结”（中文 3 句话 + English 3 sentences）

新闻内容：
{news_text}
"""

headers = {
"Content-Type": "application/json",
"Authorization": f"Bearer {DEEPSEEK_API_KEY}"
}

data = {
"model": "deepseek-chat",
"messages": [{"role": "user", "content": prompt}],
"temperature": 0.3
}

response = requests.post(DEEPSEEK_API_URL, headers=headers, json=data)
result = response.json()

return result["choices"][0]["message"]["content"]

# ----------------------
# 3. 生成美观的 HTML 邮件
# ----------------------
def generate_html(content):
html = f"""
body {{ font-family: Arial, sans-serif; line-height: 1.6; background: #f4f4f4; margin: 0; padding: 20px; }}
.container {{ max-width: 900px; margin: 0 auto; background: white; padding: 30px; border-radius: 12px; box-shadow: 0 0 20px rgba(0,0,0,0.1); }}
h1 {{ color: #2c3e50; font-size: 24px; border-bottom: 2px solid #3498db; padding-bottom: 10px; }}
h2 {{ color: #3498db; font-size: 20px; margin-top: 25px; }}
.news-item {{ margin-bottom: 20px; padding-bottom: 15px; border-bottom: 1px solid #eee; }}
.category {{ font-weight: bold; color: #e74c3c; }}
.summary {{ margin: 10px 0; }}
.implication {{ background: #f8f9fa; padding: 12px; border-radius: 8px; margin-top: 10px; border-left: 4px solid #27ae60; }}
.footer {{ margin-top: 30px; text-align: center; color: #7f8c8d; font-size: 14px; }}
每日半导体 / AI / 存储行业资讯总结（中英双语）
{content}
Generated by AI Industry Analyst (Powered by DeepSeek)
"""
return html

# ----------------------
# 4. 发送邮件
# ----------------------
def send_email(html_content):
msg = MIMEMultipart('alternative')
msg['From'] = SENDER_EMAIL
msg['To'] = RECEIVER_EMAIL
msg['Subject'] = "每日半导体 / AI / 存储行业资讯总结（中英双语）"

part = MIMEText(html_content, 'html', 'utf-8')
msg.attach(part)

try:
server = smtplib.SMTP_SSL('smtp.qq.com', 465)
server.login(SENDER_EMAIL, SENDER_PASSWORD)
server.send_message(msg)
server.quit()
print("邮件发送成功")
except Exception as e:
print(f"邮件发送失败: {e}")

# ----------------------
# 5. 微信推送（Server 酱）
# ----------------------
def send_wechat(content):
data = {
"title": "每日半导体 / AI / 存储行业资讯总结",
"desp": content[:2000] # Server 酱有长度限制
}

try:
response = requests.post(SERVERCHAN_URL, data=data)
print("微信推送成功")
except Exception as e:
print(f"微信推送失败: {e}")

# ----------------------
# 主函数
# ----------------------
def main():
news = fetch_news()
summary = summarize_news(news)
html = generate_html(summary)
send_email(html)
send_wechat(summary)

if __name__ == "__main__":
main()

